var goods = JSON.stringify([
  {
    "goodId": "1",
    "name": "Фреш апельсиновый",
    "img": "/drinks/fresh_orange.jpeg",
    "price": "99",
    "category": "1",
    "busket": "false",
    "count": "0",
  },
  {
    "goodId": "2",
    "name": "Сок яблоко добрый 1л",
    "img": "/drinks/dobri_1l_apple.png",
    "price": "120",
    "category": "1",
    "busket": "false",
    "count": "0",
  },
  {
    "goodId": "3",
    "name": "Гамбургер",
    "img": "/hamburgers/hamburger.png",
    "price": "69",
    "category": "2",
    "busket": "false",
    "count": "0",
  },
  {
    "goodId": "4",
    "name": "Салат греческий",
    "img": "/salads/grecheski.png",
    "price": "129",
    "category": "3",
    "busket": "false",
    "count": "0",
  },
  {
    "goodId": "5",
    "name": "Суп лапша",
    "img": "/sups/lapsha.png",
    "price": "89",
    "category": "4",
    "busket": "false",
    "count": "0",
  },

]);
